### ISSUE TITLE
TypeError: _RasterizeGaussiansBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 2

### ISSUE THREAD

**Issue by zhubowen1** [nfyfamr/SafeguardGS#2]
Thank you for your great work.
I am currently training a deep learning model utilizing Gaussian Splatting for scene rendering. The training process encounters an error during execution, which I have detailed below.

Traceback (most recent call last):
  File "train.py", line 296, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 93, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/zbw/SafeguardGS/gaussian_renderer/__init__.py", line 101, in render
    cov3D_precomp = cov3D_precomp)
  File "/home/zbw/anaconda3/envs/SafeguardGS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zbw/anaconda3/envs/SafeguardGS/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 262, in forward
    raster_settings,
  File "/home/zbw/anaconda3/envs/SafeguardGS/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 41, in rasterize_gaussians
    raster_settings,
TypeError: _RasterizeGaussiansBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 2

I am unable to locate the _RasterizeGaussiansBackward.forward function in the codebase to further investigate the source of the problem. Any guidance or assistance would be greatly appreciated.

**Comment by nfyfamr** [comment]
Thanks for having interest in our work, @zhubowen1. Unfortunately, this is not an expected error because there is no `_RasterizeGaussiansBackward` class defined. Could you pull the latest code and install the environment, then test again, please?

**Comment by zhubowen1** [comment]
I have resolved the problem, I found that I confused the submodules ,thank you very much.
